import {
  Bell,
  Bus,
  Clock3,
  CreditCard,
  Gift,
  Headphones,
  HelpCircle,
  History,
  Home,
  LogIn,
  MapPinned,
  Route,
  Search,
  Settings,
  Shield,
  Ticket,
  TicketPercent,
  User,
  Wallet,
} from 'lucide-react';

import type { SidebarNavGroup } from './sidebar.types';

export const sidebarNavGroups: SidebarNavGroup[] = [
  {
    id: 'main',
    label: 'Main',
    items: [
      {
        id: 'home',
        title: 'Home',
        href: '/',
        icon: Home,
        prefetch: true,
        keywords: ['dashboard', 'start'],
      },
      {
        id: 'search',
        title: 'Search Buses',
        href: '/search',
        icon: Search,
        prefetch: true,
        keywords: ['find', 'routes', 'schedule'],
      },
      {
        id: 'book',
        title: 'Book a Bus',
        href: '/buses',
        icon: Bus,
        requiresAuth: true,
        keywords: ['reserve', 'tickets'],
      },
      {
        id: 'track',
        title: 'Track Bus',
        href: '/track-bus',
        icon: MapPinned,
        badge: 'Live',
        badgeVariant: 'success',
        keywords: ['gps', 'live', 'location'],
      },
    ],
  },
  {
    id: 'bookings',
    label: 'Bookings',
    items: [
      {
        id: 'my-bookings',
        title: 'My Bookings',
        href: '/bookings',
        icon: Ticket,
        badge: 2,
        badgeVariant: 'accent',
        requiresAuth: true,
        keywords: ['reservations', 'tickets'],
      },
      {
        id: 'upcoming',
        title: 'Upcoming Trips',
        href: '/bookings/upcoming',
        icon: Clock3,
        requiresAuth: true,
        keywords: ['scheduled', 'next'],
      },
      {
        id: 'history',
        title: 'Travel History',
        href: '/bookings/history',
        icon: History,
        requiresAuth: true,
        keywords: ['past', 'trips'],
      },
      {
        id: 'saved-routes',
        title: 'Saved Routes',
        href: '/saved-routes',
        icon: Route,
        requiresAuth: true,
        keywords: ['favorites', 'bookmarks'],
      },
    ],
  },
  {
    id: 'rewards',
    label: 'Rewards',
    items: [
      {
        id: 'offers',
        title: 'Offers & Coupons',
        href: '/offers',
        icon: TicketPercent,
        badge: 'New',
        badgeVariant: 'warning',
        keywords: ['deals', 'discounts', 'promo'],
      },
      {
        id: 'rewards',
        title: 'Rewards',
        href: '/rewards',
        icon: Gift,
        requiresAuth: true,
        keywords: ['points', 'loyalty'],
      },
      {
        id: 'wallet',
        title: 'Wallet',
        href: '/wallet',
        icon: Wallet,
        requiresAuth: true,
        keywords: ['balance', 'credits'],
      },
    ],
  },
  {
    id: 'account',
    label: 'Account',
    items: [
      {
        id: 'notifications',
        title: 'Notifications',
        href: '/notifications',
        icon: Bell,
        badge: 3,
        badgeVariant: 'destructive',
        requiresAuth: true,
        keywords: ['alerts', 'messages'],
      },
      {
        id: 'profile',
        title: 'Profile',
        href: '/profile',
        icon: User,
        requiresAuth: true,
        keywords: ['account', 'me'],
      },
      {
        id: 'payments',
        title: 'Payment Methods',
        href: '/payment-methods',
        icon: CreditCard,
        requiresAuth: true,
        keywords: ['cards', 'upi'],
      },
      {
        id: 'settings',
        title: 'Settings',
        href: '/settings',
        icon: Settings,
        keywords: ['preferences', 'config'],
      },
    ],
  },
  {
    id: 'support',
    label: 'Support',
    items: [
      {
        id: 'help',
        title: 'Help Center',
        href: '/help',
        icon: HelpCircle,
        keywords: ['faq', 'guide'],
      },
      {
        id: 'support',
        title: 'Support',
        href: '/support',
        icon: Headphones,
        keywords: ['contact', 'chat'],
      },
      {
        id: 'privacy',
        title: 'Privacy & Security',
        href: '/privacy',
        icon: Shield,
        keywords: ['security', 'policy'],
      },
    ],
  },
];

export const sidebarGuestLinks = [
  {
    id: 'login',
    title: 'Sign in',
    href: '/login',
    icon: LogIn,
  },
] as const;
